# Generated by Django 6.0.8 on 2026-08-15 08:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_calendarevent"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_id", models.CharField(blank=True, max_length=20)),
                ("course", models.CharField(blank=True, max_length=100)),
                (
                    "year_of_study",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (1, "Year 1"),
                            (2, "Year 2"),
                            (3, "Year 3"),
                            (4, "Year 4"),
                            (5, "Postgraduate"),
                        ],
                        null=True,
                    ),
                ),
                ("bio", models.TextField(blank=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
