# Generated by Django 6.0.8 on 2026-08-15 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="building",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="building",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
