# Generated by Django 6.0.8 on 2026-08-15 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_building_coordinates"),
    ]

    operations = [
        migrations.AddField(
            model_name="building",
            name="website",
            field=models.URLField(blank=True),
        ),
    ]
